### ISSUE TITLE
Typescript Supporting?

### ISSUE THREAD

**Issue by chinkan** [commenthol/leaflet-rastercoords#6]
Hi,

Is this library support for typescript? I want to use in Angular 2+. Thanks :)

**Comment by commenthol** [comment]
There are no plans to offer support for typescript.

**Comment by chinkan** [comment]
could i add a typescript definition for your library? :)

**Comment by commenthol** [comment]
If you like to. Your PR is welcome.

**Comment by chinkan** [comment]
Hi @commenthol, 

I have created a new typescript definitions for your library and tried in my angular project. 
I have created a PR to DefinitelyTyped. :)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/35901

**Comment by commenthol** [comment]
Wouldn't it be better to add the type definitions within this package, instead of adding this to an external dependency?

**Comment by commenthol** [comment]
Closing due to issue resolved by PR in DefinitelyTyped package.
